eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10013
spring:
  application:
    name: cloud-sleuth-feign
  zipkin:
    base-url: http://localhost:10011